# Generated by Django 5.1.6 on 2025-02-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_callback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='callback',
            table='callback',
        ),
    ]
