from django.urls import path
from . import views
urlpatterns=[
    path('test',views.test),
    path('home',views.home),
    path('about1',views.about1),
    path('home3',views.home3),
    path('home2',views.home2),
    path('home4',views.home4),
    path('index',views.index),
    path('about',views.about),
    path('add',views.add),
    path('addcode',views.addcode),
    path('calculator',views.calculator),
    path('cal',views.cal),
    path('insert',views.insert),
    path('ins',views.ins),
    path('login',views.login),
    path('log',views.log),
    path('registration',views.registration),
    path('reg',views.reg),
    path('login2',views.login2),
    path('log2',views.log2),
    path('animation',views.animation),
    path('reg2',views.reg2),
    path('show',views.show),
    path('del/<int:id>',views.dele),
    path('edit/<int:id>',views.edit),
    path('edcode/<int:id>',views.edcode),
    path('logout', views.logout),  
]